# Generated by Django 5.0.1 on 2024-01-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_project',
            options={'verbose_name': 'Пользовательский проект', 'verbose_name_plural': 'Пользовательские проекты'},
        ),
        migrations.RenameField(
            model_name='user_project',
            old_name='name',
            new_name='title',
        ),
    ]
