# Generated by Django 5.0.1 on 2024-01-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_project_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23)),
                ('text', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Совет дня',
                'verbose_name_plural': 'Советы дня',
            },
        ),
    ]
