# Generated by Django 5.0.1 on 2024-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_all_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_tips',
            name='img',
            field=models.ImageField(upload_to='tip_imgs/'),
        ),
        migrations.AlterField(
            model_name='all_tips',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
